[package]
name = "leetcode_for_rust"
version = "0.1.2"
authors = ["Caitlin Gao <caitlin.gaoo@google.com>"]
homepage = "https://github.com/caitlingao/leetcode_rust"
repository = "https://github.com/caitlingao/leetcode_rust"
description = "leetcode for rust"
license = "MIT"
edition = "2018"

include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/lib.rs",
    "src/cd01_two_sum/mod.rs",
    "src/cd15_three_sum/mod.rs",
    "src/cd20_valid_parentheses/mod.rs",
    "src/cd206_reverse_linked_list/mod.rs",
    "src/cd232_implement_queue_using_stacks/mod.rs",
    "src/cd239_sliding_window_maximum/mod.rs",
    "src/cd242_valid_anagram/mod.rs",
    "src/cd703_kth_largest_element_in_a_stream/mod.rs",
]

[lib]
name = "leetcode_for_rust"
crate-type = ["rlib", "staticlib"]

[dependencies]
